export default {
    HOST_DIALPAD_NUMBER: 100,
    GUEST_INIT: 200,
    GUEST_PHONE_RESIZE: 201,
    GUEST_DIALPAD_NUMBER: 202,
    GUEST_PHONE_UNMOUNT: 203,
    GUEST_PHONE_READY: 204,
    GUEST_PHONE_INCOMING: 205,
    GUEST_PHONE_LOGGEDIN: 206,
};
