export default {
  AR: 'Argentina',
  AT: 'Austria',
  BH: 'Baréin',
  BR: 'Brasil',
  BG: 'Bulgaria',
  CA: 'Canadá',
  CL: 'Chile',
  CN: 'China',
  HR: 'Croacia',
  CY: 'Chipre',
  CZ: 'República Checa',
  DK: 'Dinamarca',
  DO: 'República Dominicana',
  EE: 'Estonia',
  FI: 'Finlandia',
  FR: 'Francia',
  DE: 'Alemania',
  HK: 'Hong Kong',
  HU: 'Hungría',
  IE: 'Irlanda',
  IL: 'Israel',
  IN: 'India',
  IT: 'Italia',
  JP: 'Japón',
  LV: 'Letonia',
  LT: 'Lituania',
  LU: 'Luxemburgo',
  MY: 'Malasia',
  MX: 'México',
  NL: 'Países Bajos',
  NO: 'Noruega',
  PA: 'Panamá',
  PH: 'Filipinas',
  PL: 'Polonia',
  PT: 'Portugal',
  RO: 'Rumanía',
  SK: 'Eslovaquia',
  SI: 'Eslovenia',
  ES: 'España',
  SE: 'Suecia',
  CH: 'Suiza',
  TR: 'Turquía',
  GB: 'Reino Unido',
  AU: 'Australia',
  GE: 'Georgia',
  ID: 'Indonesia',
  KE: 'Kenia',
  NG: 'Nigeria',
  PK: 'Pakistán',
  ZA: 'Sudáfrica',
  KR: 'Corea del Sur',
  SG: 'Singapur',
  TW: 'Taiwán',
  UA: 'Ucrania',
  US: 'Estados Unidos',
  VN: 'Vietnam',
  BE: 'Bélgica',
  BJ: 'Benín',
  SV: 'El Salvador',
  GH: 'Ghana',
  GR: 'Grecia',
  GN: 'Guinea',
  NZ: 'Nueva Zelanda',
  PE: 'Perú',
  PR: 'Puerto Rico',
};
