export default {
  AR: 'Argentine',
  AT: 'Autriche',
  BH: 'Bahrain',
  BR: 'Brésil',
  BG: 'Bulgarie',
  CA: 'Canada',
  CL: 'Chili',
  CN: 'Chine',
  HR: 'Croatie',
  CY: 'Chypre',
  CZ: 'République tchèque',
  DK: 'Danemark',
  DO: 'République dominicaine',
  EE: 'Estonie',
  FI: 'Finlande',
  FR: 'France',
  DE: 'Allemagne',
  HK: 'Hong Kong',
  HU: 'Hongrie',
  IE: 'Irlande',
  IL: 'Israël',
  IN: 'Inde',
  IT: 'Italie',
  JP: 'Japon',
  LV: 'Lettonie',
  LT: 'Lituanie',
  LU: 'Luxembourg',
  MY: 'Malaisie',
  MX: 'Mexique',
  NL: 'Pays-Bas',
  NO: 'Norvège',
  PA: 'Panama',
  PH: 'Philippines',
  PL: 'Pologne',
  PT: 'Portugal',
  RO: 'Roumanie',
  SK: 'Slovaquie',
  SI: 'Slovénie',
  ES: 'Espagne',
  SE: 'Suède',
  CH: 'Suisse',
  TR: 'Turquie',
  GB: 'Royaume-Uni',
  AU: 'Australie',
  GE: 'Géorgie',
  ID: 'Indonésie',
  KE: 'Kenya',
  NG: 'Nigeria',
  PK: 'Pakistan',
  ZA: 'Afrique du Sud',
  KR: 'Corée du Sud',
  SG: 'Singapour',
  TW: 'Taïwan',
  UA: 'Ukraine',
  US: 'États-Unis',
  VN: 'Vietnam',
  BE: 'Belgique',
  BJ: 'Bénin',
  SV: 'Salvador',
  GH: 'Ghana',
  GR: 'Grèce',
  GN: 'Guinée',
  NZ: 'Nouvelle-Zélande',
  PE: 'Pérou',
  PR: 'Porto Rico',
};
