export default {
  AR: 'Argentina',
  AT: 'Austria',
  BH: 'Bahrain',
  BR: 'Brasile',
  BG: 'Bulgaria',
  CA: 'Canada',
  CL: 'Cile',
  CN: 'Cina',
  HR: 'Croazia',
  CY: 'Cipro',
  CZ: 'Repubblica Ceca',
  DK: 'Danimarca',
  DO: 'Repubblica Dominicana',
  EE: 'Estonia',
  FI: 'Finlandia',
  FR: 'Francia',
  DE: 'Germania',
  HK: 'Hong Kong',
  HU: 'Ungheria',
  IE: 'Irlanda',
  IL: 'Israele',
  IN: 'India',
  IT: 'Italia',
  JP: 'Giappone',
  LV: 'Lettonia',
  LT: 'Lituania',
  LU: 'Lussemburgo',
  MY: 'Malesia',
  MX: 'Messico',
  NL: 'Paesi Bassi',
  NO: 'Norvegia',
  PA: 'Panama',
  PH: 'Filippine',
  PL: 'Polonia',
  PT: 'Portogallo',
  RO: 'Romania',
  SK: 'Slovacchia',
  SI: 'Slovenia',
  ES: 'Spagna',
  SE: 'Svezia',
  CH: 'Svizzera',
  TR: 'Turchia',
  GB: 'Regno Unito',
  AU: 'Australia',
  GE: 'Georgia',
  ID: 'Indonesia',
  KE: 'Kenya',
  NG: 'Nigeria',
  PK: 'Pakistan',
  ZA: 'Sudafrica',
  KR: 'Corea del Sud',
  SG: 'Singapore',
  TW: 'Taiwan',
  UA: 'Ucraina',
  US: 'Stati Uniti',
  VN: 'Vietnam',
  BE: 'Belgio',
  BJ: 'Benin',
  SV: 'El Salvador',
  GH: 'Ghana',
  GR: 'Grecia',
  GN: 'Guinea',
  NZ: 'Nuova Zelanda',
  PE: 'Perù',
  PR: 'Porto Rico',
};
