import { DateTimeFormatter } from 'ringcentral-integration/lib/getIntlDateTimeFormatter';

import { Call, CallLog } from './CallLog.interface';

interface CallLogPanelConfig {
  showSpinner: boolean;
  isInTransferPage: boolean;

  isWide?: boolean;
  header?: boolean;
  showSmallCallControl?: boolean;
  disableLinks?: boolean;
  useNewNotification?: boolean;
  showNotiLogButton?: boolean;
}

type CallLogPanelClasses = {
  root?: string;
  callLogCallControl?: string;
};

export interface CallLogPanelProps extends CallLogPanelConfig {
  currentLog: CallLog;
  currentLocale: string;
  goBack: (...args: any[]) => any;
  formatPhone: (...args: any[]) => any;
  onReject: (...args: any[]) => any;
  onHangup: (...args: any[]) => any;
  dateTimeFormatter: DateTimeFormatter;
  renderSaveLogButton: (...args: any[]) => JSX.Element;

  additionalInfo?: object;
  onUpdateCallLog?: (...args: any[]) => any;
  onSaveCallLog?: (...args: any[]) => any;

  renderBasicInfo?: ({
    formatPhone,
    dateTimeFormatter,
    currentLog,
  }: Pick<
    CallLogPanelProps,
    'formatPhone' | 'dateTimeFormatter' | 'currentLog'
  >) => JSX.Element;

  renderEditLogSection?: ({
    currentLocale,
    onSaveCallLog,
    onUpdateCallLog,
    currentLog,
    additionalInfo,
    subjectDropdownsTracker,
  }: Pick<
    CallLogPanelProps,
    | 'currentLocale'
    | 'onSaveCallLog'
    | 'onUpdateCallLog'
    | 'currentLog'
    | 'additionalInfo'
    | 'subjectDropdownsTracker'
  >) => JSX.Element;

  renderCallLogCallControl?: (
    status: boolean,
    telephonySessionId: string,
    isWide: boolean,
  ) => JSX.Element;

  backIcon?: string;
  currentIdentify?: string;
  subjectDropdownsTracker?: (...args: any[]) => any;
  classes?: CallLogPanelClasses;
  logNotification?: LogNotification;
  onCloseNotification?: (...args: any[]) => any;
  onDiscardNotification?: (...args: any[]) => any;
  onSaveNotification?: (...args: any[]) => any;
  onExpandNotification?: (...args: any[]) => any;
  currentNotificationIdentify?: string;
  currentSession?: object;
  pushLogPageStatus?: (...args: any[]) => any;
  shrinkNotification?: (...args: any[]) => any;
}

// Generated by https://quicktype.io

export interface LogNotification {
  showNotification: boolean;
  notificationIsExpand: boolean;
  call: Call;
  logName: string;
}
