'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  AR: 'Argentina',
  AT: 'Áustria',
  BH: 'Bahrain',
  BR: 'Brasil',
  BG: 'Bulgária',
  CA: 'Canadá',
  CL: 'Chile',
  CN: 'China',
  HR: 'Croácia',
  CY: 'Chipre',
  CZ: 'República Tcheca',
  DK: 'Dinamarca',
  DO: 'República Dominicana',
  EE: 'Estônia',
  FI: 'Finlândia',
  FR: 'França',
  DE: 'Alemanha',
  HK: 'Hong Kong',
  HU: 'Hungria',
  IE: 'Irlanda',
  IL: 'Israel',
  IN: 'Índia',
  IT: 'Itália',
  JP: 'Japão',
  LV: 'Látvia',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MY: 'Malásia',
  MX: 'México',
  NL: 'Holanda',
  NO: 'Noruega',
  PA: 'Panamá',
  PH: 'Filipinas',
  PL: 'Polônia',
  PT: 'Portugal',
  RO: 'Romênia',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  ES: 'Espanha',
  SE: 'Suécia',
  CH: 'Suíça',
  TR: 'Turquia',
  GB: 'Reino Unido',
  AU: 'Austrália',
  GE: 'Geórgia',
  ID: 'Indonésia',
  KE: 'Quênia',
  NG: 'Nigéria',
  PK: 'Paquistão',
  ZA: 'África do Sul',
  KR: 'Coreia do Sul',
  SG: 'Cingapura',
  TW: 'Taiwan',
  UA: 'Ucrânia',
  US: 'Estados Unidos',
  VN: 'Vietnã',
  BE: 'Bélgica',
  BJ: 'Benin',
  SV: 'El Salvador',
  GH: 'Gana',
  GR: 'Grécia',
  GN: 'Guiné',
  NZ: 'Nova Zelândia',
  PE: 'Peru',
  PR: 'Porto Rico'
};
//# sourceMappingURL=pt-BR.js.map
