import Enum from '../../lib/Enum';
import { moduleActionTypes } from '../../enums/moduleActionTypes';

export default new Enum(
  [
    ...Object.keys(moduleActionTypes),
    'connect',
    'registered',
    'connectError',
    'connectFailed',
    'disconnect',
    'disconnectOnInactive',
    'unregisteredOnInactive',
    'unregistered',
    'reconnect',
    'setRetryCounts',
    'updateSessions',
    'destroySessions',
    'beforeCallStart',
    'callInit',
    'callStart',
    'callResume',
    'callEnd',
    'callRing',
    'callAnswer',
    'toggleMinimized',
    'resetMinimized',
    'videoElementPrepared',
    'getUserMediaSuccess',
    'getUserMediaError',
    'setSessionCaching',
    'clearSessionCaching',
    'onholdCachedSession',
    'setIncomingAudio',
    'resetIncomingAudio',
    'setOutgoingAudio',
    'resetOutgoingAudio',
    'setRingtone',
  ],
  'webphone',
);
