import Enum from '../../lib/Enum';
import { moduleActionTypes } from '../../enums/moduleActionTypes';

export default new Enum([
  ...Object.keys(moduleActionTypes),
  'connect',
  'registered',
  'connectError',
  'connectFailed',
  'disconnect',
  'unregistered',
  'reconnect',
  'setRetryCounts',
  'updateSessions',
  'destroySessions',
  'beforeCallStart',
  'callInit',
  'callStart',
  'callEnd',
  'callRing',
  'callAnswer',
  'toggleMinimized',
  'resetMinimized',
  'videoElementPrepared',
  'getUserMediaSuccess',
  'getUserMediaError',
  'setSessionCaching',
  'clearSessionCaching',
  'onholdCachedSession',
], 'webphone');
