import AlertUI from '../../ringcentral-widgets/modules/AlertUI';
import ConnectivityBadgeUI from '../../ringcentral-widgets/modules/ConnectivityBadgeUI';
import ConnectivityManager from '../../ringcentral-widgets/modules/ConnectivityManager';
import LoginUI from '../../ringcentral-widgets/modules/LoginUI';
import OAuth from '../../ringcentral-widgets/modules/ProxyFrameOAuth';
import RegionSettingsUI from '../../ringcentral-widgets/modules/RegionSettingsUI';
import RouterInteraction from '../../ringcentral-widgets/modules/RouterInteraction';
import SettingsUI from '../../ringcentral-widgets/modules/SettingsUI';
import AccountInfo from '../modules/AccountInfo';
import Alert from '../modules/Alert';
import Auth from '../modules/Auth';
import AvailabilityMonitor from '../modules/AvailabilityMonitor';
import Brand from '../modules/Brand';
import ConnectivityMonitor from '../modules/ConnectivityMonitor';
import DateTimeFormat from '../modules/DateTimeFormat';
import DialingPlan from '../modules/DialingPlan';
import Environment from '../modules/Environment';
import ExtensionInfo from '../modules/ExtensionInfo';
import GlobalStorage from '../modules/GlobalStorage';
import Locale from '../modules/Locale';
import RateLimiter from '../modules/RateLimiter';
import RegionSettings from '../modules/RegionSettings';
import RolesAndPermissions from '../modules/RolesAndPermissions';
import Storage from '../modules/Storage';
import Subscription from '../modules/Subscription';

export interface BasePhone {
  alert: Alert;
  auth: Auth;
  brand: Brand;
  accountInfo: AccountInfo;
  connectivityMonitor: ConnectivityMonitor;
  dateTimeFormat: DateTimeFormat;
  dialingPlan: DialingPlan;
  extensionInfo: ExtensionInfo;
  environment: Environment;
  globalStorage: GlobalStorage;
  locale: Locale;
  rolesAndPermissions: RolesAndPermissions;
  regionSettings: RegionSettings;
  rateLimiter: RateLimiter;
  subscription: Subscription;
  storage: Storage;
  availabilityMonitor: AvailabilityMonitor;
  oAuth: OAuth;
  settingsUI: SettingsUI;
  connectivityManager: ConnectivityManager;
  connectivityBadgeUI: ConnectivityBadgeUI;
  routerInteraction: RouterInteraction;
  loginUI: LoginUI;
  alertUI: AlertUI;
  regionSettingsUI: RegionSettingsUI;
  [P: string]: any;
}
