import HashMap from '../../lib/HashMap';
import availability from './availabilityStatus';

//TODO: Store as JSON, and can be requested from backend server

export default new HashMap({
  '/restapi/v1.0/account': { POST: availability.LIMITED },
  '/restapi/v1.0/account/validate': { POST: availability.HIGH },
  '/restapi/v1.0/account/~': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/active-calls': { GET: availability.LIMITED },
  '/restapi/v1.0/account/~/answering-rule': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/answering-rule/{ruleId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/application-extensions': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/application-extensions/~': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/assigned-role': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/bots': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/bots/~': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/business-address': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/business-hours': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/call-log': { DELETE: availability.LIMITED, GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-log-sync': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-log/{callRecordId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-monitoring-groups': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/account/~/call-monitoring-groups/{groupId}': { DELETE: availability.HIGH, PUT: availability.HIGH },
  '/restapi/v1.0/account/~/call-monitoring-groups/{groupId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/call-monitoring-groups/{groupId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-queues': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-queues/{groupId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/call-queues/{groupId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-recording': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/call-recording/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/call-recording/custom-greetings': { DELETE: availability.LIMITED, GET: availability.HIGH },
  '/restapi/v1.0/account/~/call-recording/custom-greetings/{greetingId}': { DELETE: availability.LIMITED },
  '/restapi/v1.0/account/~/call-recording/extensions': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/department/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/department/{departmentId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/device': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/device/{deviceId}': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/device/{deviceId}/assign-line': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/device/{deviceId}/sip-info': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/dialing-plan': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/free-numbers': { GET: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/validate': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/active-calls': { GET: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/address-book': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/address-book-sync': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/address-book/contact': { GET: availability.HIGH, POST: availability.LIMITED, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/address-book/contact/{contactId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/address-book/group': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/address-book/group/{groupId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/address-book/group/{groupId}/contact': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/address-book/group/{groupId}/contact/{contactIds}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/administered-sites': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/answering-rule': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/answering-rule/{ruleId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/assigned-role': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/authz-profile': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/authz-profile/check': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/blocked-number': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/blocked-number/{blockedNumberId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/business-hours': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/call-log': { DELETE: availability.LIMITED, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/call-log-sync': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/call-log/{callRecordId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/caller-blocking': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/caller-blocking/phone-numbers': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/caller-blocking/phone-numbers/{blockedNumberId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/caller-id': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/company-pager': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/company-pager/{messageId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/company-pager/{messageId}/content/{attachmentId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/conferencing': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/credentials': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/credentials/validate': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/credentials/verify': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/delegates': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/delegation-assignments': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/device': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/direct-ring-out': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/email-to-fax': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/favorite': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/fax': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/fax/{faxIds}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/fax/{faxId}/content/{attachmentId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/forwarding-number': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/forwarding-number/{forwardingNumberId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/grant': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/greeting': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/greeting-recording-call': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/greeting-recording-call/{callId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/greeting/{greetingId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/incoming-call-info': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/intercom': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/intercom/permissions': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/meeting': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/meeting/service-info': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/meeting/{meetingId}': { DELETE: availability.HIGH, GET: availability.HIGH, PUT: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/meeting/{meetingId}/end': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/meetings-configuration': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/message-store': { DELETE: availability.LIMITED, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/message-store/counters': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/message-store/{messageId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/message-store/{messageId}/content/{attachmentId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/message-sync': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/notification-settings': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/permissions': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/phone-number': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/presence/line': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/presence/line/{lineId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/presence/permission': { GET: availability.HIGH, PUT: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/profile-image': {
    DELETE: availability.HIGH,
    GET: availability.HIGH,
    POST: availability.HIGH,
    PUT: availability.HIGH
  },
  '/restapi/v1.0/account/~/extension/~/profile-image/{scaleSize}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/reporting/settings': {
    DELETE: availability.HIGH,
    GET: availability.HIGH,
    POST: availability.HIGH,
    PUT: availability.HIGH
  },
  '/restapi/v1.0/account/~/extension/~/ring-out': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/ring-out/{ringoutId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/ringout': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/ringout/direct': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/ringout/{ringoutId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/sms': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/sms/{messageIds}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/sms/{messageId}/content/{attachmentId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/extension/~/user-groups': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/extension/~/validate': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/glip-configuration': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/greeting': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/greeting/{greetingId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/ivr': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/ivr-menus': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/ivr-menus/{ivrMenuId}': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/ivr-prompts': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/ivr-prompts/{promptId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/ivr-prompts/{promptId}/content': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/licenses': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/licenses/bulk-purchase': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/licenses/{licenseId}': { DELETE: availability.LIMITED, GET: availability.HIGH },
  '/restapi/v1.0/account/~/live-reporting/dashboards': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/account/~/live-reporting/dashboards/{dashboardId}': { DELETE: availability.HIGH, GET: availability.HIGH, PUT: availability.HIGH },
  '/restapi/v1.0/account/~/meetings-configuration': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/order': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/order/{orderId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/paging-only-groups/{pagingOnlyGroupId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/paging-only-groups/{pagingOnlyGroupId}/devices': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/paging-only-groups/{pagingOnlyGroupId}/users': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/park-locations/{parkLocationId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/park-locations/{parkLocationId}/users': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/payment-info': { GET: availability.LIMITED, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/phone-number': { GET: availability.LIMITED, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/phone-number/{phoneNumberId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/recording/{recordingId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/recording/{recordingId}/content': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/service-info': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/shared-lines-groups/{groupId}/lines': { GET: availability.HIGH, POST: availability.LIMITED, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/sites': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/sites/{siteId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/sites/{siteId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/sites/{siteId}/ivr': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/sites/{siteId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/templates': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/templates/{templateId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/templates/{templateId}/bulk-apply': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/user-group': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/user-group/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/user-group/{groupId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/user-group/{groupId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/user-role': { GET: availability.HIGH, POST: availability.LIMITED },
  '/restapi/v1.0/account/~/user-role/default': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/user-role/{roleId}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/account/~/user-role/{roleId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/account/~/validate': { POST: availability.HIGH },
  '/restapi/v1.0/account/~/voicemail-library': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/account/~/voicemail-library/broadcasts/{taskId}': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/voicemail-library/{libraryItemId}': { DELETE: availability.HIGH, GET: availability.HIGH },
  '/restapi/v1.0/account/~/voicemail-library/{libraryItemId}/content': { GET: availability.HIGH },
  '/restapi/v1.0/account/~/voicemail-library/{libraryItemId}/send': { POST: availability.LIMITED },
  '/restapi/v1.0/client-info': { GET: availability.HIGH },
  '/restapi/v1.0/client-info/banners': { GET: availability.HIGH },
  '/restapi/v1.0/client-info/banners/settings': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/client-info/custom-data/{key}': { DELETE: availability.LIMITED, GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/client-info/custom-data/{key}/content': { GET: availability.HIGH },
  '/restapi/v1.0/client-info/sip-provision': { POST: availability.HIGH },
  '/restapi/v1.0/client-info/special-number-rule': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/brand/{brandId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/country': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/country/{countryId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/device': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/fax-cover-page': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/forms/address': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/greeting': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/greeting/{greetingId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/language': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/language/{languageId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/license-types': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/location': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/permission': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/permission-category': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/permission-category/{permissionCategoryId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/permission/{permissionId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/secret-question': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/secret-question/{questionId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/service-plan/{servicePlanId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/shipping-options': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/state': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/state/{stateId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/timezone': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/timezone/{timezoneId}': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/user-role': { GET: availability.HIGH },
  '/restapi/v1.0/dictionary/user-role/{roleId}': { GET: availability.HIGH },
  '/restapi/v1.0/integration-profiles': { GET: availability.HIGH },
  '/restapi/v1.0/internal/account/info': { POST: availability.HIGH },
  '/restapi/v1.0/internal/account/~/call-monitoring-groups': { GET: availability.HIGH },
  '/restapi/v1.0/internal/account/~/call-monitoring-groups/{groupId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/account/~/call-monitoring-groups/{groupId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/internal/account/~/call-queues': { GET: availability.HIGH },
  '/restapi/v1.0/internal/account/~/call-queues/{groupId}/bulk-assign': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/account/~/call-queues/{groupId}/members': { GET: availability.HIGH },
  '/restapi/v1.0/internal/address-book': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/account/large-accounts': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/account/~/': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/account/~/business-info': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/account/~/get-all-by-account-id': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/account/~/get-all-by-account-id-lists': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/extension/': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/extension/bulk': { POST: availability.HIGH },
  '/restapi/v1.0/internal/adg/extension/~': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/federation/': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/phone-number/': { GET: availability.HIGH },
  '/restapi/v1.0/internal/adg/phone-number/bulk': { POST: availability.HIGH },
  '/restapi/v1.0/internal/adg/phone-number/bulk-by-extension-ids': { POST: availability.HIGH },
  '/restapi/v1.0/internal/adg/phone-number/{phoneNumberId}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/billing-events/process-event': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/call-recording/account/~/recording/{callRecordingId}/stream': { GET: availability.HIGH },
  '/restapi/v1.0/internal/delegates': { GET: availability.HIGH },
  '/restapi/v1.0/internal/device-order/update': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/email-to-fax/send': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/extension-permissions/check': { POST: availability.HIGH },
  '/restapi/v1.0/internal/favorite': { GET: availability.HIGH },
  '/restapi/v1.0/internal/legal-data': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/live-reporting/dashboards/permissions': { GET: availability.HIGH },
  '/restapi/v1.0/internal/message-content-stream/account/~/extension/~/message-store/{messageId}/content/{attachmentId}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/order-processor/process-device-order': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/presence': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/internal/presence-line': { GET: availability.HIGH },
  '/restapi/v1.0/internal/presence-permissions': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/internal/profile-image/account/~/extension/~/stream': { GET: availability.HIGH },
  '/restapi/v1.0/internal/profile-image/account/~/extension/~/stream/{scaleSize}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/promotion-code': { POST: availability.LIMITED },
  '/restapi/v1.0/internal/send-confirmation-email': { POST: availability.HIGH },
  '/restapi/v1.0/internal/send-sms': { POST: availability.HIGH },
  '/restapi/v1.0/internal/service-parameter/{parameterId}': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/internal/subscription/legacy/apn/add': { POST: availability.HIGH },
  '/restapi/v1.0/internal/subscription/legacy/apn/remove': { POST: availability.HIGH },
  '/restapi/v1.0/internal/tap-settings': { GET: availability.HIGH, PUT: availability.LIMITED },
  '/restapi/v1.0/internal/tester-flag': { PUT: availability.LIMITED },
  '/restapi/v1.0/internal/token-validation': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/account-info-partner/{partnerId}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/account-info/~': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/authenticate': { POST: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/authentication': { POST: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/brand-info/{brandId}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/contact-email-lookup': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/extension-info/~': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/iovation-device': { GET: availability.HIGH, POST: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/login-hash/{loginHash}': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/login-info': { GET: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/multifactor/send-code': { POST: availability.HIGH },
  '/restapi/v1.0/internal/user-auth/session-created': { POST: availability.HIGH },
  '/restapi/v1.0/notify-admin': { POST: availability.HIGH },
  '/restapi/v1.0/number-parser/parse': { POST: availability.HIGH },
  '/restapi/v1.0/number-parser/phonedata.xml': { GET: availability.HIGH },
  '/restapi/v1.0/number-pool/lookup': { POST: availability.LIMITED },
  '/restapi/v1.0/number-pool/lookup-external': { POST: availability.LIMITED },
  '/restapi/v1.0/number-pool/reserve': { POST: availability.LIMITED },
  '/restapi/v1.0/status': { GET: availability.LIMITED },
  '/restapi/{apiVersion}': { GET: availability.HIGH }
});
