/* tslint:disable */

/* eslint-disable */

/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CallDispositionProperties } from './call-disposition-properties';
import { DetailedCrmObject } from './detailed-crm-object';

/**
 *
 *
 * @export
 * @interface CallDisposition
 */
export interface CallDisposition {
  /**
   * @type {CallDispositionProperties}
   * @memberof CallDisposition
   */
  properties?: CallDispositionProperties;

  /**
   * @type {DetailedCrmObject}
   * @memberof CallDisposition
   */
  selection?: DetailedCrmObject;
  /**
   * @type {string}
   * @memberof CallDisposition
   */
  url?: string;
  /**
   * @type {string}
   * @memberof CallDisposition
   */
  id?: string;
}
