"use strict";

require("core-js/modules/es.object.define-property.js");
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CallLogDirectionEnum = void 0;
/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 *
 * @export
 * @interface CallLog
 */
/**
 * @export
 * @enum {string}
 */
var CallLogDirectionEnum = exports.CallLogDirectionEnum = /*#__PURE__*/function (CallLogDirectionEnum) {
  CallLogDirectionEnum["Inbound"] = "Inbound";
  CallLogDirectionEnum["Outbound"] = "Outbound";
  return CallLogDirectionEnum;
}({});
//# sourceMappingURL=call-log.js.map
