/* tslint:disable */

/* eslint-disable */

/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SimpleCrmObject } from './simple-crm-object';

/**
 *
 *
 * @export
 * @interface CallDispositionProperties
 */
export interface CallDispositionProperties {
  /**
   * @type {string}
   * @memberof CallDispositionProperties
   */
  id?: string;

  /**
   * @type {string}
   * @memberof CallDispositionProperties
   */
  activityType?: string;

  /**
   * @type {string}
   * @memberof CallDispositionProperties
   */
  notes?: string;

  /**
   * @type {Array<SimpleCrmObject>}
   * @memberof CallDispositionProperties
   */
  contacted?: Array<SimpleCrmObject>;

  /**
   * @type {Array<SimpleCrmObject>}
   * @memberof CallDispositionProperties
   */
  associated?: Array<SimpleCrmObject>;

  /**
   * @type {Array<SimpleCrmObject>}
   * @memberof CallDispositionProperties
   */
  regarding?: Array<SimpleCrmObject>;
}
