/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface CallLog
 */
export interface CallLog {
  /**
   * @type {string}
   * @memberof CallLog
   */
  id?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  sessionId?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  startTime?: string;

  /**
   * @type {number}
   * @memberof CallLog
   */
  duration?: number;

  /**
   * @type {string}
   * @memberof CallLog
   */
  fromNumber?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  toNumber?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  direction?: CallLogDirectionEnum;

  /**
   * @type {string}
   * @memberof CallLog
   */
  recordingUrl?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  recordingId?: string;

  /**
   * @type {string}
   * @memberof CallLog
   */
  callResult?: string;

  /**
   * @type {boolean}
   * @memberof CallLog
   */
  isExtensionCall?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum CallLogDirectionEnum {
  Inbound = 'Inbound',
  Outbound = 'Outbound',
}
