/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Call } from './call';
 /**
 * 
 *
 * @export
 * @interface CallListResponse
 */
export interface CallListResponse {

    /**
     * @type {Array<Call>}
     * @memberof CallListResponse
     */
    records?: Array<Call>;
}
