/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CallDisposition } from './call-disposition';
import { CallLog } from './call-log';
 /**
 * 
 *
 * @export
 * @interface Call
 */
export interface Call {

    /**
     * @type {string}
     * @memberof Call
     */
    id?: string;

    /**
     * @type {CallLog}
     * @memberof Call
     */
    log?: CallLog;

    /**
     * @type {CallDisposition}
     * @memberof Call
     */
    disposition?: CallDisposition;
}
