/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * The object to display
 *
 * @export
 * @interface DetailedCrmObject
 */
export interface DetailedCrmObject {

    /**
     * @type {string}
     * @memberof DetailedCrmObject
     */
    type?: string;

    /**
     * @type {string}
     * @memberof DetailedCrmObject
     */
    id?: string;

    /**
     * @type {string}
     * @memberof DetailedCrmObject
     */
    name?: string;

    /**
     * @type {string}
     * @memberof DetailedCrmObject
     */
    url?: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof DetailedCrmObject
     */
    properties?: { [key: string]: string; };
}
