/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PhoneDetails
 */
export interface PhoneDetails {

    /**
     * @type {string}
     * @memberof PhoneDetails
     */
    type?: string;

    /**
     * @type {string}
     * @memberof PhoneDetails
     */
    number?: string;
}
