/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CallLog } from './call-log';
import { PopulateCallDisposition } from './populate-call-disposition';
 /**
 *
 *
 * @export
 * @interface PopulateCall
 */
export interface PopulateCall {

    /**
     * @type {string}
     * @memberof PopulateCall
     */
    id?: string;

    /**
     * @type {boolean}
     * @memberof PopulateCall
     */
    isManual?: boolean;

    /**
     * @type {boolean}
     * @memberof PopulateCall
     */
    skipAutoCreateCrmRecord?: boolean;

    /**
     * @type {CallLog}
     * @memberof PopulateCall
     */
    log?: CallLog;

    /**
     * @type {PopulateCallDisposition}
     * @memberof PopulateCall
     */
    disposition?: PopulateCallDisposition;
}
