/* tslint:disable */

/* eslint-disable */

/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SimpleCrmObject } from './simple-crm-object';

/**
 *
 *
 * @export
 * @interface PopulateCallDisposition
 */
export interface PopulateCallDisposition {
  /**
   * @type {{ [key: string]: Array<SimpleCrmObject>; }}
   * @memberof PopulateCallDisposition
   */
  properties?: { [key: string]: Array<SimpleCrmObject> };

  /**
   * The matched objects
   *
   * @type {Array<SimpleCrmObject>}
   * @memberof PopulateCallDisposition
   */
  associations?: Array<SimpleCrmObject>;
  /**
   * @type {SimpleCrmObject}
   * @memberof PopulateCallDisposition
   */
  selection?: SimpleCrmObject;
  /**
   * the patches data for the properties which use in the call log update dispatch
   */
  patches?: {
    add: {
      [key: string]: Array<SimpleCrmObject>;
    };
    remove: {
      [key: string]: Array<SimpleCrmObject>;
    };
  };
}
