/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PhoneDetails } from './phone-details';
 /**
 * The object to display
 *
 * @export
 * @interface SimpleCrmObject
 */
export interface SimpleCrmObject {

    /**
     * @type {string}
     * @memberof SimpleCrmObject
     */
    type?: string;

    /**
     * @type {string}
     * @memberof SimpleCrmObject
     */
    id?: string;

    /**
     * @type {string}
     * @memberof SimpleCrmObject
     */
    name?: string;

    /**
     * @type {string}
     * @memberof SimpleCrmObject
     */
    url?: string;

    /**
     * @type {Array<PhoneDetails>}
     * @memberof SimpleCrmObject
     */
    phones?: Array<PhoneDetails>;
}
