/* tslint:disable */
/* eslint-disable */
/**
 * CRM Platform Adaptor
 * CRM Platform Adaptor API
 *
 * OpenAPI spec version: 1.0.20230808
 * Contact: integration.dev@ringcentral.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SimpleCrmObject } from './simple-crm-object';
 /**
 *
 *
 * @export
 * @interface SmsConversation
 */
export interface SmsConversation {

    /**
     * @type {string}
     * @memberof SmsConversation
     */
    id?: string;

    /**
     * @type {string}
     * @memberof SmsConversation
     */
    ownerName?: string;

    /**
     * @type {SimpleCrmObject}
     * @memberof SmsConversation
     */
    selection?: SimpleCrmObject;

    /**
     * @type {Array<SimpleCrmObject>}
     * @memberof SmsConversation
     */
    associations?: Array<SimpleCrmObject>;

    /**
     * Last logged to
     *
     * @type {string}
     * @memberof SmsConversation
     */
    lastLoggedTime?: string;
}
