export declare const dayjsLanguagesMap: {
    'en-US': string;
    'de-DE': string;
    'en-AU': string;
    'en-GB': string;
    'es-419': string;
    'es-ES': string;
    'fr-CA': string;
    'fr-FR': string;
    'it-IT': string;
    'ja-JP': string;
    'pt-BR': string;
    'pt-PT': string;
    'zh-CN': string;
    'zh-HK': string;
    'zh-TW': string;
    'nl-NL': string;
    'ko-KR': string;
    'fi-FI': string;
};
export declare const setDayjsLocale: (locale: string) => void;
