name: CI Pipeline

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn workspace @ringcentral-integration/babel-settings test --coverage
      - name: Babel Settings Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/babel-settings/coverage/lcov.info
          flag-name: babel-settings
          parallel: true
      - run: yarn workspace @ringcentral-integration/phone-number test --coverage
      - name: Phone Number Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/phone-number/coverage/lcov.info
          flag-name: phone-number
          parallel: true
      - run: yarn workspace @ringcentral-integration/i18n test --coverage
      - name: I18n Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/i18n/coverage/lcov.info
          flag-name: i18n
          parallel: true
      - run: yarn workspace @ringcentral-integration/locale-loader test --coverage
      - name: locale-loader Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/locale-loader/coverage/lcov.info
          flag-name: locale-loader
          parallel: true
      - run: yarn workspace @ringcentral-integration/utils test --coverage
      - name: Core Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/utils/coverage/lcov.info
          flag-name: utils
          parallel: true
      - run: yarn workspace @ringcentral-integration/core test --coverage
      - name: Core Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/core/coverage/lcov.info
          flag-name: core
          parallel: true
      - run: yarn workspace @ringcentral-integration/react-hooks test --coverage
      - name: Core Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/react-hooks/coverage/lcov.info
          flag-name: react-hooks
          parallel: true
      - run: yarn workspace @ringcentral-integration/commons test --coverage
      - name: Commons Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/ringcentral-integration/coverage/lcov.info
          flag-name: commons
          parallel: true
      - run: yarn workspace @ringcentral-integration/widgets test --coverage
      - name: Widgets Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/ringcentral-widgets/coverage/lcov.info
          flag-name: widgets
          parallel: true
      - run: yarn workspace ringcentral-widgets-test test --ci --coverage --updateSnapshot
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Widgets Integration Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/ringcentral-widgets-test/coverage/lcov.info
          flag-name: widgets-integration
          parallel: true
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  branch-release:
    needs: tests
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: yarn
      - run: yarn workspace @ringcentral-integration/utils release
      - name: Utils Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: utils-release
          FOLDER: release/utils
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/core release
      - name: Core Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: core-release
          FOLDER: release/core
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/i18n release
      - name: I18n Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: i18n-release
          FOLDER: release/i18n
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/i18n-dayjs release
      - name: I18n Dayjs Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: i18n-dayjs-release
          FOLDER: release/i18n-dayjs
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/react-hooks release
      - name: React Hooks Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: react-hooks-release
          FOLDER: release/react-hooks
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/locale-loader release
      - name: Locale Loader Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: locale-loader-release
          FOLDER: release/locale-loader
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/phone-number release
      - name: Phone Number Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: phone-number-release
          FOLDER: release/phone-number
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/commons release
      - name: Commons Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: commons-release
          FOLDER: release/ringcentral-integration
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/widgets release
      - name: Widgets Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: widgets-release
          FOLDER: release/ringcentral-widgets
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/engage-voice-widgets release
      - name: Engage Voice-widgets Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: engage-voice-widgets-release
          FOLDER: release/engage-voice-widgets
          CLEAN: true
      - run: yarn workspace @ringcentral-integration/glip-widgets release
      - name: Glip Widgets Branch Release
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: glip-widgets-release
          FOLDER: release/glip-widgets
          CLEAN: true
